export const VALIDATION_SUCCESS = "VALIDATION_SUCCESS";
export const VALIDATION_ERROR = "VALIDATION_ERROR";
export const VALIDATION_WARNING = "VALIDATION_WARNING";

export const VALIDATION_LEVELS = [VALIDATION_SUCCESS, VALIDATION_WARNING, VALIDATION_ERROR];
